---
- name: Cluster prep
  hosts: k3s_cluster
  gather_facts: true
  become: true
  roles:
    - role: prereq
    - role: airgap
    - role: raspberrypi

- name: Setup K3S server
  hosts: server
  gather_facts: false
  become: true
  roles:
    - role: k3s_server

- name: Setup K3S agent
  hosts: agent
  gather_facts: false
  become: true
  roles:
    - role: k3s_agent

- name: Label agent nodes as workers
  hosts: server
  become: true
  gather_facts: false
  tasks:
    - name: Gather facts from agent nodes
      setup:
      delegate_to: "{{ item }}"
      loop: "{{ groups['agent'] }}"
    - name: Label agent nodes as workers
      command: >
        kubectl label node {{ hostvars[item]['ansible_hostname'] }} node-role.kubernetes.io/worker=worker --overwrite
      loop: "{{ groups['agent'] }}"